### ISSUE TITLE
How to get MMM-RemoteControl menu for SmartWebDisplay?

### ISSUE THREAD

**Issue by RahulPillai22** [AgP42/MMM-SmartWebDisplay#9]
I have followed your tutorial and installed the SmartWebDisplay, as well as the remote control and all the other controls for the remote, are working properly but I am unable to see the menu for SmartWebDisplay on the remote, which will has the buttons play, next, previous, pause, stop.
Please help.

**Comment by AgP42** [comment]
Hello, 

you are right, there is obviously an error on the documentation, I forget to change the link for the installation, so you where installing the official version and not the one modified...

Please use the following link instead and I will correct the documentation asap : 
```
bash -c "$(curl -s https://raw.githubusercontent.com/AgP42/MMM-Remote-Control/master/installer.sh)"
```

or for manual installation : 
```
cd ~/MagicMirror/modules # adapt directory if you are using a different one
git clone https://github.com/AgP42/MMM-Remote-Control.git
cd MMM-Remote-Control
npm install
```

Better now ? 

Sorry for that stupid mistake ! ;-)

**Comment by AgP42** [comment]
(update of the documentation done !)

**Comment by RahulPillai22** [comment]
> Hello,
> 
> you are right, there is obviously an error on the documentation, I forget to change the link for the installation, so you where installing the official version and not the one modified...
> 
> Please use the following link instead and I will correct the documentation asap :
> 
> ```
> bash -c "$(curl -s https://raw.githubusercontent.com/AgP42/MMM-Remote-Control/master/installer.sh)"
> ```
> 
> or for manual installation :
> 
> ```
> cd ~/MagicMirror/modules # adapt directory if you are using a different one
> git clone https://github.com/AgP42/MMM-Remote-Control.git
> cd MMM-Remote-Control
> npm install
> ```
> 
> Better now ?
> 
> Sorry for that stupid mistake ! ;-)

Thanks for the quick reply,
So I deleted the remote control module from /modules folder and then installed it using the above-provided code but still, I don't see the options for the smartWebDisplay

**Comment by AgP42** [comment]
Ok, so I did it too to reproduce the issue and I find the error on the installation script. Normally it would have worked with the manual installation. 

Anyway I now corrected the installation script and test it again and it is now ok on my installation. 

Could you please try again now ?  

Sorry for the inconvenience and thanks for the debugging help !

**Comment by RahulPillai22** [comment]
So the auto script install still isn't working but I tried the manual install and it worked now I am using the remote to control a youtube playlist via the smart web display.
But using the remote when I try commands like Pause, next, previous it doesn't work,
On pause, there is no response.
On previous, the video stops and nothing shows till we click play and then the playlist starts again, same with the next button.
Stop works properly.
Am I missing some steps of the installation?
Sorry to bother you this much 😅

**Comment by AgP42** [comment]
Hi, 

I am surprised that the installation script was not working this time, did you get any error ? 
But good if you were able to install it anyway. 

Their is a misunderstanding about the "next/prev/pause/stop" commands, they cannot apply to the YouTube playlist itself, because the module don't even know you are displaying YouTube. 
Thoses commands apply to the several URL you can set on the configuration file. 

So you could, instead of using a YouTube playlist, add each video on the config list, then you will be able to use the "next/prev/pause/stop" commands. 
For the "pause" behavior", it will stop the rotation of the URL (if a rotation timer was set), but cannot "pause" the video itself...

If you want to use only YouTube videos, their are several other modules dedicated to it, for example : https://github.com/nitpum/MMM-EmbedYoutube, https://github.com/justjim1220/MMM-RandomYouTubePlayer, https://github.com/kevinatown/MMM-Screencast, https://github.com/C4TFLY/MMM-YouTube-API, maybe one of those will better fit your need. 

Good luck, 
AgP

**Comment by RahulPillai22** [comment]
> Hi,
> 
> I am surprised that the installation script was not working this time, did you get any error ?
> But good if you were able to install it anyway.
> 
> Their is a misunderstanding about the "next/prev/pause/stop" commands, they cannot apply to the YouTube playlist itself, because the module don't even know you are displaying YouTube.
> Thoses commands apply to the several URL you can set on the configuration file.
> 
> So you could, instead of using a YouTube playlist, add each video on the config list, then you will be able to use the "next/prev/pause/stop" commands.
> For the "pause" behavior", it will stop the rotation of the URL (if a rotation timer was set), but cannot "pause" the video itself...
> 
> If you want to use only YouTube videos, their are several other modules dedicated to it, for example : https://github.com/nitpum/MMM-EmbedYoutube, https://github.com/justjim1220/MMM-RandomYouTubePlayer, https://github.com/kevinatown/MMM-Screencast, https://github.com/C4TFLY/MMM-YouTube-API, maybe one of those will better fit your need.
> 
> Good luck,
> AgP

Thanks for the quick reply again!

As for the auto-install, no I didn't get any errors, just the option for smart web display wasnt showing but on using manual installation it was working.

And for the options, sorry it was my misunderstanding and thanks for correcting it and giving the other options.

Thanks,
Rahul Pillai

**Comment by AgP42** [comment]
Your're welcome :-)
